name: Check compilation
run-name: ${{ github.actor }} ${{ github.branch }} | Check compilation
on:
  push:
    branches:
      - "**"

env:
  EXECUTABLE: "vengine"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: true

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: ./tools/install-dependencies.sh build

      - name: Check compilation
        run: ./tools/build.sh build

      - name: Check binary
        run: |
          if [[ ! -x "./${EXECUTABLE}" ]]; then
            echo "Error: Binary ${EXECUTABLE} not found."
            exit 1
          fi
