name: Update docs
run-name: ${{github.actor}} Update docs
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libxkbcommon-dev libxinerama-dev libxcursor-dev libxi-dev libglm-dev libglfw3-dev glslang-tools doxygen doxygen-latex

      - name: Update docs
        run: ./build.sh doc

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "[bot] doc generator"
          commit_message: "[DOCS]: Update docs"
          commit_options: "--no-verify"
          file_pattern: "docs/VEngine.pdf"

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./.doxygen/html
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4