name: VEngine
run-name: ${{github.actor}} VEngine
on:
  push:
    branches:
      - "**"

env:
  EXECUTABLE: "vengine"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Vulkan dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglm-dev libglfw3-dev glslang-tools

      - name: Check compilation
        run: |
          mkdir ./build && cd ./build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Check binary
        run: |
          if [[ ! -x "./${EXECUTABLE}" ]]; then
          echo "Error: Binary ${EXECUTABLE} not found."
          exit 1
          fi
